// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MServiceAddrbook.proto

/*
Package mserviceaddrbook is a generated protocol buffer package.

It is generated from these files:
	MServiceAddrbook.proto

It has these top-level messages:
	Party
	PartyWrapper
	Address
	Phone
	CreatePartyRequest
	CreatePartyResponse
	UpdatePartyRequest
	UpdatePartyResponse
	DeletePartyRequest
	DeletePartyResponse
	GetPartyRequest
	GetPartyResponse
	GetPartiesRequest
	GetPartiesResponse
	GetPartyWrapperRequest
	GetPartyWrapperResponse
	CreateAddressRequest
	CreateAddressResponse
	UpdateAddressRequest
	UpdateAddressResponse
	DeleteAddressRequest
	DeleteAddressResponse
	GetAddressRequest
	GetAddressResponse
	CreatePhoneRequest
	CreatePhoneResponse
	UpdatePhoneRequest
	UpdatePhoneResponse
	DeletePhoneRequest
	DeletePhoneResponse
	GetPhoneRequest
	GetPhoneResponse
	GetServerVersionRequest
	GetServerVersionResponse
*/
package mserviceaddrbook

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import dml "github.com/gaterace/dml-go/pkg/dml"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// address book party type
type PartyType int32

const (
	// party type is unknown
	PartyType_UnknownParty PartyType = 0
	// party is a person
	PartyType_Person PartyType = 1
	// party is a business
	PartyType_Business PartyType = 2
)

var PartyType_name = map[int32]string{
	0: "UnknownParty",
	1: "Person",
	2: "Business",
}
var PartyType_value = map[string]int32{
	"UnknownParty": 0,
	"Person":       1,
	"Business":     2,
}

func (x PartyType) String() string {
	return proto.EnumName(PartyType_name, int32(x))
}
func (PartyType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// address book address type
type AddressType int32

const (
	// address type is unknown
	AddressType_UnknownAddress AddressType = 0
	// address is home address
	AddressType_Home AddressType = 1
	// address is shipping address
	AddressType_Shipping AddressType = 2
)

var AddressType_name = map[int32]string{
	0: "UnknownAddress",
	1: "Home",
	2: "Shipping",
}
var AddressType_value = map[string]int32{
	"UnknownAddress": 0,
	"Home":           1,
	"Shipping":       2,
}

func (x AddressType) String() string {
	return proto.EnumName(AddressType_name, int32(x))
}
func (AddressType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// address book phone type
type PhoneType int32

const (
	// phone type is unknown
	PhoneType_UnknownPhone PhoneType = 0
	// phone is home phone
	PhoneType_HomePhone PhoneType = 1
	// phone is work phone
	PhoneType_WorkPhone PhoneType = 2
	// phone is cell phone
	PhoneType_CellPhone PhoneType = 3
)

var PhoneType_name = map[int32]string{
	0: "UnknownPhone",
	1: "HomePhone",
	2: "WorkPhone",
	3: "CellPhone",
}
var PhoneType_value = map[string]int32{
	"UnknownPhone": 0,
	"HomePhone":    1,
	"WorkPhone":    2,
	"CellPhone":    3,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}
func (PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// address book party entity
type Party struct {
	// party identifier
	PartyId int64 `protobuf:"varint,1,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// creation date
	Created *dml.DateTime `protobuf:"bytes,2,opt,name=created" json:"created,omitempty"`
	// modification date
	Modified *dml.DateTime `protobuf:"bytes,3,opt,name=modified" json:"modified,omitempty"`
	// deletion date
	Deleted *dml.DateTime `protobuf:"bytes,4,opt,name=deleted" json:"deleted,omitempty"`
	// has record been deleted?
	IsDeleted bool `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted" json:"is_deleted,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,6,opt,name=version" json:"version,omitempty"`
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,7,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// type of party record, int value of PartyType
	PartyType int32 `protobuf:"varint,8,opt,name=party_type,json=partyType" json:"party_type,omitempty"`
	// string representation of party_type
	PartyTypeName string `protobuf:"bytes,9,opt,name=party_type_name,json=partyTypeName" json:"party_type_name,omitempty"`
	// party last name
	LastName string `protobuf:"bytes,10,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	// party middle name
	MiddleName string `protobuf:"bytes,11,opt,name=middle_name,json=middleName" json:"middle_name,omitempty"`
	// party first name
	FirstName string `protobuf:"bytes,12,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	// party nickname
	Nickname string `protobuf:"bytes,13,opt,name=nickname" json:"nickname,omitempty"`
	// party company
	Company string `protobuf:"bytes,14,opt,name=company" json:"company,omitempty"`
	// party email
	Email string `protobuf:"bytes,15,opt,name=email" json:"email,omitempty"`
}

func (m *Party) Reset()                    { *m = Party{} }
func (m *Party) String() string            { return proto.CompactTextString(m) }
func (*Party) ProtoMessage()               {}
func (*Party) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Party) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *Party) GetCreated() *dml.DateTime {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Party) GetModified() *dml.DateTime {
	if m != nil {
		return m.Modified
	}
	return nil
}

func (m *Party) GetDeleted() *dml.DateTime {
	if m != nil {
		return m.Deleted
	}
	return nil
}

func (m *Party) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func (m *Party) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Party) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *Party) GetPartyType() int32 {
	if m != nil {
		return m.PartyType
	}
	return 0
}

func (m *Party) GetPartyTypeName() string {
	if m != nil {
		return m.PartyTypeName
	}
	return ""
}

func (m *Party) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Party) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Party) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Party) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Party) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Party) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// address book party entity wrapper
type PartyWrapper struct {
	// party identifier
	PartyId int64 `protobuf:"varint,1,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// creation date
	Created *dml.DateTime `protobuf:"bytes,2,opt,name=created" json:"created,omitempty"`
	// modification date
	Modified *dml.DateTime `protobuf:"bytes,3,opt,name=modified" json:"modified,omitempty"`
	// deletion date
	Deleted *dml.DateTime `protobuf:"bytes,4,opt,name=deleted" json:"deleted,omitempty"`
	// has record been deleted?
	IsDeleted bool `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted" json:"is_deleted,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,6,opt,name=version" json:"version,omitempty"`
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,7,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// type of party record, int value of PartyType
	PartyType int32 `protobuf:"varint,8,opt,name=party_type,json=partyType" json:"party_type,omitempty"`
	// string representation of party_type
	PartyTypeName string `protobuf:"bytes,9,opt,name=party_type_name,json=partyTypeName" json:"party_type_name,omitempty"`
	// party last name
	LastName string `protobuf:"bytes,10,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	// party middle name
	MiddleName string `protobuf:"bytes,11,opt,name=middle_name,json=middleName" json:"middle_name,omitempty"`
	// party first name
	FirstName string `protobuf:"bytes,12,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	// party nickname
	Nickname string `protobuf:"bytes,13,opt,name=nickname" json:"nickname,omitempty"`
	// party company
	Company string `protobuf:"bytes,14,opt,name=company" json:"company,omitempty"`
	// party email
	Email string `protobuf:"bytes,15,opt,name=email" json:"email,omitempty"`
	// list address book address objects
	Addresses []*Address `protobuf:"bytes,16,rep,name=addresses" json:"addresses,omitempty"`
	// list address book phone objects
	Phones []*Phone `protobuf:"bytes,17,rep,name=phones" json:"phones,omitempty"`
}

func (m *PartyWrapper) Reset()                    { *m = PartyWrapper{} }
func (m *PartyWrapper) String() string            { return proto.CompactTextString(m) }
func (*PartyWrapper) ProtoMessage()               {}
func (*PartyWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PartyWrapper) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *PartyWrapper) GetCreated() *dml.DateTime {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *PartyWrapper) GetModified() *dml.DateTime {
	if m != nil {
		return m.Modified
	}
	return nil
}

func (m *PartyWrapper) GetDeleted() *dml.DateTime {
	if m != nil {
		return m.Deleted
	}
	return nil
}

func (m *PartyWrapper) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func (m *PartyWrapper) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PartyWrapper) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *PartyWrapper) GetPartyType() int32 {
	if m != nil {
		return m.PartyType
	}
	return 0
}

func (m *PartyWrapper) GetPartyTypeName() string {
	if m != nil {
		return m.PartyTypeName
	}
	return ""
}

func (m *PartyWrapper) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *PartyWrapper) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *PartyWrapper) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *PartyWrapper) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *PartyWrapper) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *PartyWrapper) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PartyWrapper) GetAddresses() []*Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *PartyWrapper) GetPhones() []*Phone {
	if m != nil {
		return m.Phones
	}
	return nil
}

// address book address entity
type Address struct {
	// party identifier
	PartyId int64 `protobuf:"varint,1,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// type of address record, int value of AddressType
	AddressType int32 `protobuf:"varint,2,opt,name=address_type,json=addressType" json:"address_type,omitempty"`
	// creation date
	Created *dml.DateTime `protobuf:"bytes,3,opt,name=created" json:"created,omitempty"`
	// modification date
	Modified *dml.DateTime `protobuf:"bytes,4,opt,name=modified" json:"modified,omitempty"`
	// deletion date
	Deleted *dml.DateTime `protobuf:"bytes,5,opt,name=deleted" json:"deleted,omitempty"`
	// has record been deleted?
	IsDeleted bool `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted" json:"is_deleted,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,7,opt,name=version" json:"version,omitempty"`
	// string representation of address_type
	AddressTypeName string `protobuf:"bytes,8,opt,name=address_type_name,json=addressTypeName" json:"address_type_name,omitempty"`
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,9,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// postal address line 1
	Address_1 string `protobuf:"bytes,10,opt,name=address_1,json=address1" json:"address_1,omitempty"`
	// postal address line 2
	Address_2 string `protobuf:"bytes,11,opt,name=address_2,json=address2" json:"address_2,omitempty"`
	// postal city
	City string `protobuf:"bytes,12,opt,name=city" json:"city,omitempty"`
	// postal state
	State string `protobuf:"bytes,13,opt,name=state" json:"state,omitempty"`
	// postal code
	PostalCode string `protobuf:"bytes,14,opt,name=postal_code,json=postalCode" json:"postal_code,omitempty"`
	// country code
	CountryCode string `protobuf:"bytes,15,opt,name=country_code,json=countryCode" json:"country_code,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Address) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *Address) GetAddressType() int32 {
	if m != nil {
		return m.AddressType
	}
	return 0
}

func (m *Address) GetCreated() *dml.DateTime {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Address) GetModified() *dml.DateTime {
	if m != nil {
		return m.Modified
	}
	return nil
}

func (m *Address) GetDeleted() *dml.DateTime {
	if m != nil {
		return m.Deleted
	}
	return nil
}

func (m *Address) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func (m *Address) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Address) GetAddressTypeName() string {
	if m != nil {
		return m.AddressTypeName
	}
	return ""
}

func (m *Address) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *Address) GetAddress_1() string {
	if m != nil {
		return m.Address_1
	}
	return ""
}

func (m *Address) GetAddress_2() string {
	if m != nil {
		return m.Address_2
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Address) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

// address book phone entity
type Phone struct {
	// party identifier
	PartyId int64 `protobuf:"varint,1,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// type of phone record, int value of PhoneType
	PhoneType int32 `protobuf:"varint,2,opt,name=phone_type,json=phoneType" json:"phone_type,omitempty"`
	// creation date
	Created *dml.DateTime `protobuf:"bytes,3,opt,name=created" json:"created,omitempty"`
	// modification date
	Modified *dml.DateTime `protobuf:"bytes,4,opt,name=modified" json:"modified,omitempty"`
	// deletion date
	Deleted *dml.DateTime `protobuf:"bytes,5,opt,name=deleted" json:"deleted,omitempty"`
	// has record been deleted?
	IsDeleted bool `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted" json:"is_deleted,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,7,opt,name=version" json:"version,omitempty"`
	// string representation of phone_type
	PhoneTypeName string `protobuf:"bytes,8,opt,name=phone_type_name,json=phoneTypeName" json:"phone_type_name,omitempty"`
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,9,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// phone number
	PhoneNumber string `protobuf:"bytes,10,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
}

func (m *Phone) Reset()                    { *m = Phone{} }
func (m *Phone) String() string            { return proto.CompactTextString(m) }
func (*Phone) ProtoMessage()               {}
func (*Phone) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Phone) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *Phone) GetPhoneType() int32 {
	if m != nil {
		return m.PhoneType
	}
	return 0
}

func (m *Phone) GetCreated() *dml.DateTime {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Phone) GetModified() *dml.DateTime {
	if m != nil {
		return m.Modified
	}
	return nil
}

func (m *Phone) GetDeleted() *dml.DateTime {
	if m != nil {
		return m.Deleted
	}
	return nil
}

func (m *Phone) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func (m *Phone) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Phone) GetPhoneTypeName() string {
	if m != nil {
		return m.PhoneTypeName
	}
	return ""
}

func (m *Phone) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *Phone) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

// request parameters for method create_party
type CreatePartyRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// type of party record, int value of PartyType
	PartyType int32 `protobuf:"varint,2,opt,name=party_type,json=partyType" json:"party_type,omitempty"`
	// party last name
	LastName string `protobuf:"bytes,3,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	// party middle name
	MiddleName string `protobuf:"bytes,4,opt,name=middle_name,json=middleName" json:"middle_name,omitempty"`
	// party first name
	FirstName string `protobuf:"bytes,5,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	// party nickname
	Nickname string `protobuf:"bytes,6,opt,name=nickname" json:"nickname,omitempty"`
	// party company
	Company string `protobuf:"bytes,7,opt,name=company" json:"company,omitempty"`
	// party email
	Email string `protobuf:"bytes,8,opt,name=email" json:"email,omitempty"`
}

func (m *CreatePartyRequest) Reset()                    { *m = CreatePartyRequest{} }
func (m *CreatePartyRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePartyRequest) ProtoMessage()               {}
func (*CreatePartyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreatePartyRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *CreatePartyRequest) GetPartyType() int32 {
	if m != nil {
		return m.PartyType
	}
	return 0
}

func (m *CreatePartyRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreatePartyRequest) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *CreatePartyRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreatePartyRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreatePartyRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *CreatePartyRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// response parameters for method create_party
type CreatePartyResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	// party identifier
	PartyId int64 `protobuf:"varint,4,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
}

func (m *CreatePartyResponse) Reset()                    { *m = CreatePartyResponse{} }
func (m *CreatePartyResponse) String() string            { return proto.CompactTextString(m) }
func (*CreatePartyResponse) ProtoMessage()               {}
func (*CreatePartyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreatePartyResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CreatePartyResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *CreatePartyResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *CreatePartyResponse) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

// request parameters for method update_party
type UpdatePartyRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// party identifier
	PartyId int64 `protobuf:"varint,2,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	// type of party record, int value of PartyType
	PartyType int32 `protobuf:"varint,4,opt,name=party_type,json=partyType" json:"party_type,omitempty"`
	// party last name
	LastName string `protobuf:"bytes,5,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	// party middle name
	MiddleName string `protobuf:"bytes,6,opt,name=middle_name,json=middleName" json:"middle_name,omitempty"`
	// party first name
	FirstName string `protobuf:"bytes,7,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	// party nickname
	Nickname string `protobuf:"bytes,8,opt,name=nickname" json:"nickname,omitempty"`
	// party company
	Company string `protobuf:"bytes,9,opt,name=company" json:"company,omitempty"`
	// party email
	Email string `protobuf:"bytes,10,opt,name=email" json:"email,omitempty"`
}

func (m *UpdatePartyRequest) Reset()                    { *m = UpdatePartyRequest{} }
func (m *UpdatePartyRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePartyRequest) ProtoMessage()               {}
func (*UpdatePartyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdatePartyRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *UpdatePartyRequest) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *UpdatePartyRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UpdatePartyRequest) GetPartyType() int32 {
	if m != nil {
		return m.PartyType
	}
	return 0
}

func (m *UpdatePartyRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdatePartyRequest) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *UpdatePartyRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdatePartyRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UpdatePartyRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *UpdatePartyRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// response parameters for method update_party
type UpdatePartyResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *UpdatePartyResponse) Reset()                    { *m = UpdatePartyResponse{} }
func (m *UpdatePartyResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdatePartyResponse) ProtoMessage()               {}
func (*UpdatePartyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdatePartyResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *UpdatePartyResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *UpdatePartyResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// request parameters for method delete_party
type DeletePartyRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// party identifier
	PartyId int64 `protobuf:"varint,2,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *DeletePartyRequest) Reset()                    { *m = DeletePartyRequest{} }
func (m *DeletePartyRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePartyRequest) ProtoMessage()               {}
func (*DeletePartyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeletePartyRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *DeletePartyRequest) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *DeletePartyRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// response parameters for method delete_party
type DeletePartyResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *DeletePartyResponse) Reset()                    { *m = DeletePartyResponse{} }
func (m *DeletePartyResponse) String() string            { return proto.CompactTextString(m) }
func (*DeletePartyResponse) ProtoMessage()               {}
func (*DeletePartyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeletePartyResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *DeletePartyResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *DeletePartyResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// request parameters for method get_party
type GetPartyRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// party identifier
	PartyId int64 `protobuf:"varint,2,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
}

func (m *GetPartyRequest) Reset()                    { *m = GetPartyRequest{} }
func (m *GetPartyRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPartyRequest) ProtoMessage()               {}
func (*GetPartyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetPartyRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *GetPartyRequest) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

// response parameters for method get_party
type GetPartyResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// address book party object
	Party *Party `protobuf:"bytes,3,opt,name=party" json:"party,omitempty"`
}

func (m *GetPartyResponse) Reset()                    { *m = GetPartyResponse{} }
func (m *GetPartyResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPartyResponse) ProtoMessage()               {}
func (*GetPartyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetPartyResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetPartyResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetPartyResponse) GetParty() *Party {
	if m != nil {
		return m.Party
	}
	return nil
}

// request parameters for method get_parties
type GetPartiesRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
}

func (m *GetPartiesRequest) Reset()                    { *m = GetPartiesRequest{} }
func (m *GetPartiesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPartiesRequest) ProtoMessage()               {}
func (*GetPartiesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetPartiesRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

// response parameters for method get_parties
type GetPartiesResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// list address book party objects
	Parties []*Party `protobuf:"bytes,3,rep,name=parties" json:"parties,omitempty"`
}

func (m *GetPartiesResponse) Reset()                    { *m = GetPartiesResponse{} }
func (m *GetPartiesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPartiesResponse) ProtoMessage()               {}
func (*GetPartiesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetPartiesResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetPartiesResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetPartiesResponse) GetParties() []*Party {
	if m != nil {
		return m.Parties
	}
	return nil
}

// request parameters for method get_party_wrapper
type GetPartyWrapperRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// party identifier
	PartyId int64 `protobuf:"varint,2,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
}

func (m *GetPartyWrapperRequest) Reset()                    { *m = GetPartyWrapperRequest{} }
func (m *GetPartyWrapperRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPartyWrapperRequest) ProtoMessage()               {}
func (*GetPartyWrapperRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetPartyWrapperRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *GetPartyWrapperRequest) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

// response parameters for method get_party_wrapper
type GetPartyWrapperResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// address book party wrapper object
	PartyWrapper *PartyWrapper `protobuf:"bytes,3,opt,name=party_wrapper,json=partyWrapper" json:"party_wrapper,omitempty"`
}

func (m *GetPartyWrapperResponse) Reset()                    { *m = GetPartyWrapperResponse{} }
func (m *GetPartyWrapperResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPartyWrapperResponse) ProtoMessage()               {}
func (*GetPartyWrapperResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetPartyWrapperResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetPartyWrapperResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetPartyWrapperResponse) GetPartyWrapper() *PartyWrapper {
	if m != nil {
		return m.PartyWrapper
	}
	return nil
}

// request parameters for method create_address
type CreateAddressRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// party identifier
	PartyId int64 `protobuf:"varint,2,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// type of address record, int value of AddressType
	AddressType int32 `protobuf:"varint,3,opt,name=address_type,json=addressType" json:"address_type,omitempty"`
	// postal address line 1
	Address_1 string `protobuf:"bytes,4,opt,name=address_1,json=address1" json:"address_1,omitempty"`
	// postal address line 2
	Address_2 string `protobuf:"bytes,5,opt,name=address_2,json=address2" json:"address_2,omitempty"`
	// postal city
	City string `protobuf:"bytes,6,opt,name=city" json:"city,omitempty"`
	// postal state
	State string `protobuf:"bytes,7,opt,name=state" json:"state,omitempty"`
	// postal code
	PostalCode string `protobuf:"bytes,8,opt,name=postal_code,json=postalCode" json:"postal_code,omitempty"`
	// country code
	CountryCode string `protobuf:"bytes,9,opt,name=country_code,json=countryCode" json:"country_code,omitempty"`
}

func (m *CreateAddressRequest) Reset()                    { *m = CreateAddressRequest{} }
func (m *CreateAddressRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAddressRequest) ProtoMessage()               {}
func (*CreateAddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CreateAddressRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *CreateAddressRequest) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *CreateAddressRequest) GetAddressType() int32 {
	if m != nil {
		return m.AddressType
	}
	return 0
}

func (m *CreateAddressRequest) GetAddress_1() string {
	if m != nil {
		return m.Address_1
	}
	return ""
}

func (m *CreateAddressRequest) GetAddress_2() string {
	if m != nil {
		return m.Address_2
	}
	return ""
}

func (m *CreateAddressRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CreateAddressRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CreateAddressRequest) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *CreateAddressRequest) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

// response parameters for method create_address
type CreateAddressResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *CreateAddressResponse) Reset()                    { *m = CreateAddressResponse{} }
func (m *CreateAddressResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAddressResponse) ProtoMessage()               {}
func (*CreateAddressResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *CreateAddressResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CreateAddressResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *CreateAddressResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// request parameters for method update_address
type UpdateAddressRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// party identifier
	PartyId int64 `protobuf:"varint,2,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// type of address record, int value of AddressType
	AddressType int32 `protobuf:"varint,3,opt,name=address_type,json=addressType" json:"address_type,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	// postal address line 1
	Address_1 string `protobuf:"bytes,5,opt,name=address_1,json=address1" json:"address_1,omitempty"`
	// postal address line 2
	Address_2 string `protobuf:"bytes,6,opt,name=address_2,json=address2" json:"address_2,omitempty"`
	// postal city
	City string `protobuf:"bytes,7,opt,name=city" json:"city,omitempty"`
	// postal state
	State string `protobuf:"bytes,8,opt,name=state" json:"state,omitempty"`
	// postal code
	PostalCode string `protobuf:"bytes,9,opt,name=postal_code,json=postalCode" json:"postal_code,omitempty"`
	// country code
	CountryCode string `protobuf:"bytes,10,opt,name=country_code,json=countryCode" json:"country_code,omitempty"`
}

func (m *UpdateAddressRequest) Reset()                    { *m = UpdateAddressRequest{} }
func (m *UpdateAddressRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateAddressRequest) ProtoMessage()               {}
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *UpdateAddressRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *UpdateAddressRequest) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *UpdateAddressRequest) GetAddressType() int32 {
	if m != nil {
		return m.AddressType
	}
	return 0
}

func (m *UpdateAddressRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UpdateAddressRequest) GetAddress_1() string {
	if m != nil {
		return m.Address_1
	}
	return ""
}

func (m *UpdateAddressRequest) GetAddress_2() string {
	if m != nil {
		return m.Address_2
	}
	return ""
}

func (m *UpdateAddressRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *UpdateAddressRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *UpdateAddressRequest) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *UpdateAddressRequest) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

// response parameters for method update_address
type UpdateAddressResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *UpdateAddressResponse) Reset()                    { *m = UpdateAddressResponse{} }
func (m *UpdateAddressResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateAddressResponse) ProtoMessage()               {}
func (*UpdateAddressResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *UpdateAddressResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *UpdateAddressResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *UpdateAddressResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// request parameters for method delete_address
type DeleteAddressRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// party identifier
	PartyId int64 `protobuf:"varint,2,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// type of address record, int value of AddressType
	AddressType int32 `protobuf:"varint,3,opt,name=address_type,json=addressType" json:"address_type,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
}

func (m *DeleteAddressRequest) Reset()                    { *m = DeleteAddressRequest{} }
func (m *DeleteAddressRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressRequest) ProtoMessage()               {}
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *DeleteAddressRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *DeleteAddressRequest) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *DeleteAddressRequest) GetAddressType() int32 {
	if m != nil {
		return m.AddressType
	}
	return 0
}

func (m *DeleteAddressRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// response parameters for method delete_address
type DeleteAddressResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *DeleteAddressResponse) Reset()                    { *m = DeleteAddressResponse{} }
func (m *DeleteAddressResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressResponse) ProtoMessage()               {}
func (*DeleteAddressResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *DeleteAddressResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *DeleteAddressResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *DeleteAddressResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// request parameters for method get_address
type GetAddressRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// party identifier
	PartyId int64 `protobuf:"varint,2,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// type of address record, int value of AddressType
	AddressType int32 `protobuf:"varint,3,opt,name=address_type,json=addressType" json:"address_type,omitempty"`
}

func (m *GetAddressRequest) Reset()                    { *m = GetAddressRequest{} }
func (m *GetAddressRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAddressRequest) ProtoMessage()               {}
func (*GetAddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *GetAddressRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *GetAddressRequest) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *GetAddressRequest) GetAddressType() int32 {
	if m != nil {
		return m.AddressType
	}
	return 0
}

// response parameters for method get_address
type GetAddressResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// address book address object
	Address *Address `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
}

func (m *GetAddressResponse) Reset()                    { *m = GetAddressResponse{} }
func (m *GetAddressResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAddressResponse) ProtoMessage()               {}
func (*GetAddressResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *GetAddressResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetAddressResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetAddressResponse) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

// request parameters for method create_phone
type CreatePhoneRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// party identifier
	PartyId int64 `protobuf:"varint,2,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// type of phone record, int value of PhoneType
	PhoneType int32 `protobuf:"varint,3,opt,name=phone_type,json=phoneType" json:"phone_type,omitempty"`
	// phone number
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
}

func (m *CreatePhoneRequest) Reset()                    { *m = CreatePhoneRequest{} }
func (m *CreatePhoneRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePhoneRequest) ProtoMessage()               {}
func (*CreatePhoneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *CreatePhoneRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *CreatePhoneRequest) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *CreatePhoneRequest) GetPhoneType() int32 {
	if m != nil {
		return m.PhoneType
	}
	return 0
}

func (m *CreatePhoneRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

// response parameters for method create_phone
type CreatePhoneResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *CreatePhoneResponse) Reset()                    { *m = CreatePhoneResponse{} }
func (m *CreatePhoneResponse) String() string            { return proto.CompactTextString(m) }
func (*CreatePhoneResponse) ProtoMessage()               {}
func (*CreatePhoneResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *CreatePhoneResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CreatePhoneResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *CreatePhoneResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// request parameters for method update_phone
type UpdatePhoneRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// party identifier
	PartyId int64 `protobuf:"varint,2,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// type of phone record, int value of PhoneType
	PhoneType int32 `protobuf:"varint,3,opt,name=phone_type,json=phoneType" json:"phone_type,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	// phone number
	PhoneNumber string `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
}

func (m *UpdatePhoneRequest) Reset()                    { *m = UpdatePhoneRequest{} }
func (m *UpdatePhoneRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePhoneRequest) ProtoMessage()               {}
func (*UpdatePhoneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *UpdatePhoneRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *UpdatePhoneRequest) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *UpdatePhoneRequest) GetPhoneType() int32 {
	if m != nil {
		return m.PhoneType
	}
	return 0
}

func (m *UpdatePhoneRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UpdatePhoneRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

// response parameters for method update_phone
type UpdatePhoneResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *UpdatePhoneResponse) Reset()                    { *m = UpdatePhoneResponse{} }
func (m *UpdatePhoneResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdatePhoneResponse) ProtoMessage()               {}
func (*UpdatePhoneResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *UpdatePhoneResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *UpdatePhoneResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *UpdatePhoneResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// request parameters for method delete_phone
type DeletePhoneRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// party identifier
	PartyId int64 `protobuf:"varint,2,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// type of phone record, int value of PhoneType
	PhoneType int32 `protobuf:"varint,3,opt,name=phone_type,json=phoneType" json:"phone_type,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
}

func (m *DeletePhoneRequest) Reset()                    { *m = DeletePhoneRequest{} }
func (m *DeletePhoneRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePhoneRequest) ProtoMessage()               {}
func (*DeletePhoneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *DeletePhoneRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *DeletePhoneRequest) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *DeletePhoneRequest) GetPhoneType() int32 {
	if m != nil {
		return m.PhoneType
	}
	return 0
}

func (m *DeletePhoneRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// response parameters for method delete_phone
type DeletePhoneResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// version of this record
	Version int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *DeletePhoneResponse) Reset()                    { *m = DeletePhoneResponse{} }
func (m *DeletePhoneResponse) String() string            { return proto.CompactTextString(m) }
func (*DeletePhoneResponse) ProtoMessage()               {}
func (*DeletePhoneResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *DeletePhoneResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *DeletePhoneResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *DeletePhoneResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// request parameters for method get_phone
type GetPhoneRequest struct {
	// mservice account identifier
	MserviceId int64 `protobuf:"varint,1,opt,name=mservice_id,json=mserviceId" json:"mservice_id,omitempty"`
	// party identifier
	PartyId int64 `protobuf:"varint,2,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	// type of phone record, int value of PhoneType
	PhoneType int32 `protobuf:"varint,3,opt,name=phone_type,json=phoneType" json:"phone_type,omitempty"`
}

func (m *GetPhoneRequest) Reset()                    { *m = GetPhoneRequest{} }
func (m *GetPhoneRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPhoneRequest) ProtoMessage()               {}
func (*GetPhoneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *GetPhoneRequest) GetMserviceId() int64 {
	if m != nil {
		return m.MserviceId
	}
	return 0
}

func (m *GetPhoneRequest) GetPartyId() int64 {
	if m != nil {
		return m.PartyId
	}
	return 0
}

func (m *GetPhoneRequest) GetPhoneType() int32 {
	if m != nil {
		return m.PhoneType
	}
	return 0
}

// response parameters for method get_phone
type GetPhoneResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// address book phone object
	Phone *Phone `protobuf:"bytes,3,opt,name=phone" json:"phone,omitempty"`
}

func (m *GetPhoneResponse) Reset()                    { *m = GetPhoneResponse{} }
func (m *GetPhoneResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPhoneResponse) ProtoMessage()               {}
func (*GetPhoneResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *GetPhoneResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetPhoneResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetPhoneResponse) GetPhone() *Phone {
	if m != nil {
		return m.Phone
	}
	return nil
}

// request parameters for method get_server_version
type GetServerVersionRequest struct {
	// placeholder param to avoid empty message
	DummyParam int32 `protobuf:"varint,1,opt,name=dummy_param,json=dummyParam" json:"dummy_param,omitempty"`
}

func (m *GetServerVersionRequest) Reset()                    { *m = GetServerVersionRequest{} }
func (m *GetServerVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetServerVersionRequest) ProtoMessage()               {}
func (*GetServerVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *GetServerVersionRequest) GetDummyParam() int32 {
	if m != nil {
		return m.DummyParam
	}
	return 0
}

// response parameters for method get_server_version
type GetServerVersionResponse struct {
	// method result code
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	// text error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// version level of server
	ServerVersion string `protobuf:"bytes,3,opt,name=server_version,json=serverVersion" json:"server_version,omitempty"`
	// server uptime in seconds
	ServerUptime int64 `protobuf:"varint,4,opt,name=server_uptime,json=serverUptime" json:"server_uptime,omitempty"`
}

func (m *GetServerVersionResponse) Reset()                    { *m = GetServerVersionResponse{} }
func (m *GetServerVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetServerVersionResponse) ProtoMessage()               {}
func (*GetServerVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *GetServerVersionResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetServerVersionResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetServerVersionResponse) GetServerVersion() string {
	if m != nil {
		return m.ServerVersion
	}
	return ""
}

func (m *GetServerVersionResponse) GetServerUptime() int64 {
	if m != nil {
		return m.ServerUptime
	}
	return 0
}

func init() {
	proto.RegisterType((*Party)(nil), "org.gaterace.mservice.addrbook.Party")
	proto.RegisterType((*PartyWrapper)(nil), "org.gaterace.mservice.addrbook.PartyWrapper")
	proto.RegisterType((*Address)(nil), "org.gaterace.mservice.addrbook.Address")
	proto.RegisterType((*Phone)(nil), "org.gaterace.mservice.addrbook.Phone")
	proto.RegisterType((*CreatePartyRequest)(nil), "org.gaterace.mservice.addrbook.CreatePartyRequest")
	proto.RegisterType((*CreatePartyResponse)(nil), "org.gaterace.mservice.addrbook.CreatePartyResponse")
	proto.RegisterType((*UpdatePartyRequest)(nil), "org.gaterace.mservice.addrbook.UpdatePartyRequest")
	proto.RegisterType((*UpdatePartyResponse)(nil), "org.gaterace.mservice.addrbook.UpdatePartyResponse")
	proto.RegisterType((*DeletePartyRequest)(nil), "org.gaterace.mservice.addrbook.DeletePartyRequest")
	proto.RegisterType((*DeletePartyResponse)(nil), "org.gaterace.mservice.addrbook.DeletePartyResponse")
	proto.RegisterType((*GetPartyRequest)(nil), "org.gaterace.mservice.addrbook.GetPartyRequest")
	proto.RegisterType((*GetPartyResponse)(nil), "org.gaterace.mservice.addrbook.GetPartyResponse")
	proto.RegisterType((*GetPartiesRequest)(nil), "org.gaterace.mservice.addrbook.GetPartiesRequest")
	proto.RegisterType((*GetPartiesResponse)(nil), "org.gaterace.mservice.addrbook.GetPartiesResponse")
	proto.RegisterType((*GetPartyWrapperRequest)(nil), "org.gaterace.mservice.addrbook.GetPartyWrapperRequest")
	proto.RegisterType((*GetPartyWrapperResponse)(nil), "org.gaterace.mservice.addrbook.GetPartyWrapperResponse")
	proto.RegisterType((*CreateAddressRequest)(nil), "org.gaterace.mservice.addrbook.CreateAddressRequest")
	proto.RegisterType((*CreateAddressResponse)(nil), "org.gaterace.mservice.addrbook.CreateAddressResponse")
	proto.RegisterType((*UpdateAddressRequest)(nil), "org.gaterace.mservice.addrbook.UpdateAddressRequest")
	proto.RegisterType((*UpdateAddressResponse)(nil), "org.gaterace.mservice.addrbook.UpdateAddressResponse")
	proto.RegisterType((*DeleteAddressRequest)(nil), "org.gaterace.mservice.addrbook.DeleteAddressRequest")
	proto.RegisterType((*DeleteAddressResponse)(nil), "org.gaterace.mservice.addrbook.DeleteAddressResponse")
	proto.RegisterType((*GetAddressRequest)(nil), "org.gaterace.mservice.addrbook.GetAddressRequest")
	proto.RegisterType((*GetAddressResponse)(nil), "org.gaterace.mservice.addrbook.GetAddressResponse")
	proto.RegisterType((*CreatePhoneRequest)(nil), "org.gaterace.mservice.addrbook.CreatePhoneRequest")
	proto.RegisterType((*CreatePhoneResponse)(nil), "org.gaterace.mservice.addrbook.CreatePhoneResponse")
	proto.RegisterType((*UpdatePhoneRequest)(nil), "org.gaterace.mservice.addrbook.UpdatePhoneRequest")
	proto.RegisterType((*UpdatePhoneResponse)(nil), "org.gaterace.mservice.addrbook.UpdatePhoneResponse")
	proto.RegisterType((*DeletePhoneRequest)(nil), "org.gaterace.mservice.addrbook.DeletePhoneRequest")
	proto.RegisterType((*DeletePhoneResponse)(nil), "org.gaterace.mservice.addrbook.DeletePhoneResponse")
	proto.RegisterType((*GetPhoneRequest)(nil), "org.gaterace.mservice.addrbook.GetPhoneRequest")
	proto.RegisterType((*GetPhoneResponse)(nil), "org.gaterace.mservice.addrbook.GetPhoneResponse")
	proto.RegisterType((*GetServerVersionRequest)(nil), "org.gaterace.mservice.addrbook.GetServerVersionRequest")
	proto.RegisterType((*GetServerVersionResponse)(nil), "org.gaterace.mservice.addrbook.GetServerVersionResponse")
	proto.RegisterEnum("org.gaterace.mservice.addrbook.PartyType", PartyType_name, PartyType_value)
	proto.RegisterEnum("org.gaterace.mservice.addrbook.AddressType", AddressType_name, AddressType_value)
	proto.RegisterEnum("org.gaterace.mservice.addrbook.PhoneType", PhoneType_name, PhoneType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MServiceAddrbook service

type MServiceAddrbookClient interface {
	// create new party
	CreateParty(ctx context.Context, in *CreatePartyRequest, opts ...grpc.CallOption) (*CreatePartyResponse, error)
	// update an existing party
	UpdateParty(ctx context.Context, in *UpdatePartyRequest, opts ...grpc.CallOption) (*UpdatePartyResponse, error)
	// delete an existing party
	DeleteParty(ctx context.Context, in *DeletePartyRequest, opts ...grpc.CallOption) (*DeletePartyResponse, error)
	// get party by id
	GetParty(ctx context.Context, in *GetPartyRequest, opts ...grpc.CallOption) (*GetPartyResponse, error)
	// get parties by mservice id
	GetParties(ctx context.Context, in *GetPartiesRequest, opts ...grpc.CallOption) (*GetPartiesResponse, error)
	// get party wrapper by id
	GetPartyWrapper(ctx context.Context, in *GetPartyWrapperRequest, opts ...grpc.CallOption) (*GetPartyWrapperResponse, error)
	// create a new address for a party
	CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...grpc.CallOption) (*CreateAddressResponse, error)
	// update an existing address for a party
	UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...grpc.CallOption) (*UpdateAddressResponse, error)
	// delete an existing address for a party
	DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...grpc.CallOption) (*DeleteAddressResponse, error)
	// get an address for a party by id
	GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*GetAddressResponse, error)
	// create a new  phone
	CreatePhone(ctx context.Context, in *CreatePhoneRequest, opts ...grpc.CallOption) (*CreatePhoneResponse, error)
	// update an existing phone
	UpdatePhone(ctx context.Context, in *UpdatePhoneRequest, opts ...grpc.CallOption) (*UpdatePhoneResponse, error)
	// delete an existing phone
	DeletePhone(ctx context.Context, in *DeletePhoneRequest, opts ...grpc.CallOption) (*DeletePhoneResponse, error)
	// get a phone for a party by id
	GetPhone(ctx context.Context, in *GetPhoneRequest, opts ...grpc.CallOption) (*GetPhoneResponse, error)
	// get current server version and uptime - health check
	GetServerVersion(ctx context.Context, in *GetServerVersionRequest, opts ...grpc.CallOption) (*GetServerVersionResponse, error)
}

type mServiceAddrbookClient struct {
	cc *grpc.ClientConn
}

func NewMServiceAddrbookClient(cc *grpc.ClientConn) MServiceAddrbookClient {
	return &mServiceAddrbookClient{cc}
}

func (c *mServiceAddrbookClient) CreateParty(ctx context.Context, in *CreatePartyRequest, opts ...grpc.CallOption) (*CreatePartyResponse, error) {
	out := new(CreatePartyResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/create_party", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) UpdateParty(ctx context.Context, in *UpdatePartyRequest, opts ...grpc.CallOption) (*UpdatePartyResponse, error) {
	out := new(UpdatePartyResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/update_party", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) DeleteParty(ctx context.Context, in *DeletePartyRequest, opts ...grpc.CallOption) (*DeletePartyResponse, error) {
	out := new(DeletePartyResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/delete_party", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) GetParty(ctx context.Context, in *GetPartyRequest, opts ...grpc.CallOption) (*GetPartyResponse, error) {
	out := new(GetPartyResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/get_party", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) GetParties(ctx context.Context, in *GetPartiesRequest, opts ...grpc.CallOption) (*GetPartiesResponse, error) {
	out := new(GetPartiesResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/get_parties", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) GetPartyWrapper(ctx context.Context, in *GetPartyWrapperRequest, opts ...grpc.CallOption) (*GetPartyWrapperResponse, error) {
	out := new(GetPartyWrapperResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/get_party_wrapper", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...grpc.CallOption) (*CreateAddressResponse, error) {
	out := new(CreateAddressResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/create_address", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...grpc.CallOption) (*UpdateAddressResponse, error) {
	out := new(UpdateAddressResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/update_address", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...grpc.CallOption) (*DeleteAddressResponse, error) {
	out := new(DeleteAddressResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/delete_address", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*GetAddressResponse, error) {
	out := new(GetAddressResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/get_address", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) CreatePhone(ctx context.Context, in *CreatePhoneRequest, opts ...grpc.CallOption) (*CreatePhoneResponse, error) {
	out := new(CreatePhoneResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/create_phone", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) UpdatePhone(ctx context.Context, in *UpdatePhoneRequest, opts ...grpc.CallOption) (*UpdatePhoneResponse, error) {
	out := new(UpdatePhoneResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/update_phone", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) DeletePhone(ctx context.Context, in *DeletePhoneRequest, opts ...grpc.CallOption) (*DeletePhoneResponse, error) {
	out := new(DeletePhoneResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/delete_phone", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) GetPhone(ctx context.Context, in *GetPhoneRequest, opts ...grpc.CallOption) (*GetPhoneResponse, error) {
	out := new(GetPhoneResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/get_phone", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mServiceAddrbookClient) GetServerVersion(ctx context.Context, in *GetServerVersionRequest, opts ...grpc.CallOption) (*GetServerVersionResponse, error) {
	out := new(GetServerVersionResponse)
	err := grpc.Invoke(ctx, "/org.gaterace.mservice.addrbook.MServiceAddrbook/get_server_version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MServiceAddrbook service

type MServiceAddrbookServer interface {
	// create new party
	CreateParty(context.Context, *CreatePartyRequest) (*CreatePartyResponse, error)
	// update an existing party
	UpdateParty(context.Context, *UpdatePartyRequest) (*UpdatePartyResponse, error)
	// delete an existing party
	DeleteParty(context.Context, *DeletePartyRequest) (*DeletePartyResponse, error)
	// get party by id
	GetParty(context.Context, *GetPartyRequest) (*GetPartyResponse, error)
	// get parties by mservice id
	GetParties(context.Context, *GetPartiesRequest) (*GetPartiesResponse, error)
	// get party wrapper by id
	GetPartyWrapper(context.Context, *GetPartyWrapperRequest) (*GetPartyWrapperResponse, error)
	// create a new address for a party
	CreateAddress(context.Context, *CreateAddressRequest) (*CreateAddressResponse, error)
	// update an existing address for a party
	UpdateAddress(context.Context, *UpdateAddressRequest) (*UpdateAddressResponse, error)
	// delete an existing address for a party
	DeleteAddress(context.Context, *DeleteAddressRequest) (*DeleteAddressResponse, error)
	// get an address for a party by id
	GetAddress(context.Context, *GetAddressRequest) (*GetAddressResponse, error)
	// create a new  phone
	CreatePhone(context.Context, *CreatePhoneRequest) (*CreatePhoneResponse, error)
	// update an existing phone
	UpdatePhone(context.Context, *UpdatePhoneRequest) (*UpdatePhoneResponse, error)
	// delete an existing phone
	DeletePhone(context.Context, *DeletePhoneRequest) (*DeletePhoneResponse, error)
	// get a phone for a party by id
	GetPhone(context.Context, *GetPhoneRequest) (*GetPhoneResponse, error)
	// get current server version and uptime - health check
	GetServerVersion(context.Context, *GetServerVersionRequest) (*GetServerVersionResponse, error)
}

func RegisterMServiceAddrbookServer(s *grpc.Server, srv MServiceAddrbookServer) {
	s.RegisterService(&_MServiceAddrbook_serviceDesc, srv)
}

func _MServiceAddrbook_CreateParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).CreateParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/CreateParty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).CreateParty(ctx, req.(*CreatePartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_UpdateParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).UpdateParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/UpdateParty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).UpdateParty(ctx, req.(*UpdatePartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_DeleteParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).DeleteParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/DeleteParty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).DeleteParty(ctx, req.(*DeletePartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_GetParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).GetParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/GetParty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).GetParty(ctx, req.(*GetPartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_GetParties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).GetParties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/GetParties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).GetParties(ctx, req.(*GetPartiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_GetPartyWrapper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartyWrapperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).GetPartyWrapper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/GetPartyWrapper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).GetPartyWrapper(ctx, req.(*GetPartyWrapperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_CreateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).CreateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/CreateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).CreateAddress(ctx, req.(*CreateAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_UpdateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).UpdateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/UpdateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).UpdateAddress(ctx, req.(*UpdateAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_DeleteAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).DeleteAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/DeleteAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).DeleteAddress(ctx, req.(*DeleteAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_GetAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).GetAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/GetAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).GetAddress(ctx, req.(*GetAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_CreatePhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).CreatePhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/CreatePhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).CreatePhone(ctx, req.(*CreatePhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_UpdatePhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).UpdatePhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/UpdatePhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).UpdatePhone(ctx, req.(*UpdatePhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_DeletePhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).DeletePhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/DeletePhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).DeletePhone(ctx, req.(*DeletePhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_GetPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).GetPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/GetPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).GetPhone(ctx, req.(*GetPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MServiceAddrbook_GetServerVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MServiceAddrbookServer).GetServerVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.gaterace.mservice.addrbook.MServiceAddrbook/GetServerVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MServiceAddrbookServer).GetServerVersion(ctx, req.(*GetServerVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MServiceAddrbook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "org.gaterace.mservice.addrbook.MServiceAddrbook",
	HandlerType: (*MServiceAddrbookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create_party",
			Handler:    _MServiceAddrbook_CreateParty_Handler,
		},
		{
			MethodName: "update_party",
			Handler:    _MServiceAddrbook_UpdateParty_Handler,
		},
		{
			MethodName: "delete_party",
			Handler:    _MServiceAddrbook_DeleteParty_Handler,
		},
		{
			MethodName: "get_party",
			Handler:    _MServiceAddrbook_GetParty_Handler,
		},
		{
			MethodName: "get_parties",
			Handler:    _MServiceAddrbook_GetParties_Handler,
		},
		{
			MethodName: "get_party_wrapper",
			Handler:    _MServiceAddrbook_GetPartyWrapper_Handler,
		},
		{
			MethodName: "create_address",
			Handler:    _MServiceAddrbook_CreateAddress_Handler,
		},
		{
			MethodName: "update_address",
			Handler:    _MServiceAddrbook_UpdateAddress_Handler,
		},
		{
			MethodName: "delete_address",
			Handler:    _MServiceAddrbook_DeleteAddress_Handler,
		},
		{
			MethodName: "get_address",
			Handler:    _MServiceAddrbook_GetAddress_Handler,
		},
		{
			MethodName: "create_phone",
			Handler:    _MServiceAddrbook_CreatePhone_Handler,
		},
		{
			MethodName: "update_phone",
			Handler:    _MServiceAddrbook_UpdatePhone_Handler,
		},
		{
			MethodName: "delete_phone",
			Handler:    _MServiceAddrbook_DeletePhone_Handler,
		},
		{
			MethodName: "get_phone",
			Handler:    _MServiceAddrbook_GetPhone_Handler,
		},
		{
			MethodName: "get_server_version",
			Handler:    _MServiceAddrbook_GetServerVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "MServiceAddrbook.proto",
}

func init() { proto.RegisterFile("MServiceAddrbook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5a, 0xcb, 0x8f, 0xdb, 0x54,
	0x17, 0xaf, 0xf3, 0xf6, 0x49, 0x32, 0x93, 0xb9, 0x9d, 0xaf, 0x9f, 0xbf, 0x54, 0xfd, 0xbe, 0xa9,
	0x3f, 0x95, 0x0e, 0x23, 0x14, 0xda, 0xb4, 0x50, 0x1e, 0x42, 0x68, 0xfa, 0x10, 0x14, 0xa9, 0xd5,
	0x90, 0xb6, 0x54, 0x62, 0x13, 0xb9, 0xf1, 0xed, 0xd4, 0x4c, 0xfc, 0xc0, 0xd7, 0xe9, 0x90, 0x45,
	0x77, 0x48, 0x88, 0x0d, 0x48, 0xb0, 0x42, 0x88, 0x7f, 0xa0, 0x62, 0x81, 0xd8, 0xb0, 0xe7, 0x5f,
	0x61, 0xc5, 0x96, 0x05, 0x3b, 0x24, 0x74, 0x1f, 0x76, 0x6c, 0xc7, 0xb1, 0x6f, 0xa4, 0x34, 0x3c,
	0xc4, 0x6e, 0xee, 0xb9, 0xf7, 0x3c, 0x7f, 0xc7, 0xe7, 0x9e, 0x73, 0x33, 0x70, 0xea, 0xd6, 0x1d,
	0xec, 0x3f, 0xb6, 0x46, 0x78, 0xdf, 0x34, 0xfd, 0x07, 0xae, 0x7b, 0xd4, 0xf3, 0x7c, 0x37, 0x70,
	0xd1, 0x7f, 0x5d, 0xff, 0xb0, 0x77, 0x68, 0x04, 0xd8, 0x37, 0x46, 0xb8, 0x67, 0x13, 0x7e, 0xa8,
	0x67, 0x88, 0x53, 0x5d, 0x74, 0xdd, 0x1e, 0xdf, 0xf8, 0x28, 0xc0, 0x0e, 0xb1, 0x5c, 0x87, 0xf3,
	0xe8, 0x3f, 0x97, 0xa1, 0x7a, 0x60, 0xf8, 0xc1, 0x14, 0xfd, 0x07, 0x1a, 0x1e, 0xfd, 0x63, 0x68,
	0x99, 0x9a, 0xb2, 0xa3, 0xec, 0x96, 0x07, 0x75, 0xb6, 0xbe, 0x69, 0xa2, 0xf3, 0x50, 0x1f, 0xf9,
	0xd8, 0x08, 0xb0, 0xa9, 0x95, 0x76, 0x94, 0xdd, 0x66, 0xbf, 0xdd, 0x33, 0xed, 0x71, 0xef, 0xba,
	0x11, 0xe0, 0xbb, 0x96, 0x8d, 0x07, 0xe1, 0x2e, 0x7a, 0x1e, 0x1a, 0xb6, 0x6b, 0x5a, 0x0f, 0x2d,
	0x6c, 0x6a, 0xe5, 0xac, 0x93, 0xd1, 0x36, 0x95, 0x69, 0xe2, 0x31, 0xa6, 0x32, 0x2b, 0x99, 0x32,
	0xc5, 0x2e, 0x3a, 0x03, 0x60, 0x91, 0x61, 0x78, 0xb6, 0xba, 0xa3, 0xec, 0x36, 0x06, 0xaa, 0x45,
	0xae, 0x8b, 0x6d, 0x0d, 0xea, 0x8f, 0xb1, 0x4f, 0x3d, 0xd2, 0x6a, 0x3b, 0xca, 0x6e, 0x75, 0x10,
	0x2e, 0xd1, 0xff, 0xa0, 0x19, 0xc6, 0x80, 0xfa, 0x54, 0x67, 0x3e, 0x41, 0x48, 0xba, 0xc9, 0x24,
	0x73, 0x8f, 0x83, 0xa9, 0x87, 0xb5, 0x06, 0xe3, 0x56, 0x19, 0xe5, 0xee, 0xd4, 0xc3, 0xe8, 0x39,
	0xd8, 0x9c, 0x6d, 0x0f, 0x1d, 0xc3, 0xc6, 0x9a, 0xba, 0xa3, 0xec, 0xaa, 0x83, 0x76, 0x74, 0xe6,
	0xb6, 0x61, 0x63, 0x74, 0x1a, 0xd4, 0xb1, 0x41, 0x02, 0x7e, 0x02, 0xd8, 0x89, 0x06, 0x25, 0xb0,
	0x4d, 0x6a, 0x84, 0x65, 0x9a, 0x63, 0x21, 0xa0, 0xc9, 0xb6, 0x81, 0x93, 0xd8, 0x81, 0x33, 0x00,
	0x0f, 0x2d, 0x3f, 0x64, 0x6f, 0xb1, 0x7d, 0x95, 0x51, 0xd8, 0x76, 0x17, 0x1a, 0x8e, 0x35, 0x3a,
	0x62, 0x9b, 0x6d, 0x2e, 0x3b, 0x5c, 0x53, 0xd7, 0x47, 0xae, 0xed, 0x19, 0xce, 0x54, 0xdb, 0x60,
	0x5b, 0xe1, 0x12, 0x6d, 0x43, 0x15, 0xdb, 0x86, 0x35, 0xd6, 0x36, 0x19, 0x9d, 0x2f, 0xf4, 0x5f,
	0x2b, 0xd0, 0x62, 0x58, 0xdf, 0xf7, 0x0d, 0xcf, 0xc3, 0xfe, 0x3f, 0x90, 0xff, 0xdd, 0x21, 0x47,
	0x37, 0x40, 0xa5, 0x9f, 0x3f, 0x26, 0x04, 0x13, 0xad, 0xb3, 0x53, 0xde, 0x6d, 0xf6, 0xcf, 0xf7,
	0xf2, 0xcb, 0x44, 0x6f, 0x9f, 0x33, 0x0c, 0x66, 0x9c, 0xe8, 0x0d, 0xa8, 0x79, 0x8f, 0x5c, 0x07,
	0x13, 0x6d, 0x8b, 0xc9, 0x38, 0x57, 0x24, 0xe3, 0x80, 0x9e, 0x1e, 0x08, 0x26, 0xfd, 0x97, 0x32,
	0xd4, 0x85, 0xd4, 0xbc, 0x9c, 0x3b, 0x0b, 0x2d, 0xa1, 0x92, 0xc3, 0x53, 0x62, 0xf0, 0x34, 0x05,
	0x8d, 0x01, 0x14, 0x4b, 0xcb, 0xb2, 0x74, 0x5a, 0x56, 0xa4, 0xd3, 0xb2, 0xba, 0x44, 0x5a, 0xd6,
	0x72, 0xd2, 0xb2, 0x9e, 0x4c, 0xcb, 0x3d, 0xd8, 0x8a, 0x3b, 0xc6, 0x71, 0x6f, 0x30, 0x9c, 0x36,
	0x63, 0xde, 0x45, 0xd9, 0x13, 0x4b, 0x61, 0x75, 0x2e, 0x85, 0x4f, 0x47, 0x90, 0x0e, 0x2f, 0x86,
	0xb9, 0x27, 0x08, 0x17, 0xe3, 0x9b, 0x7d, 0x91, 0x79, 0xe1, 0x66, 0x1f, 0x21, 0xa8, 0x8c, 0xac,
	0x60, 0x2a, 0x32, 0x8e, 0xfd, 0x4d, 0xd3, 0x86, 0x04, 0x46, 0x10, 0x66, 0x1a, 0x5f, 0x50, 0x23,
	0x3c, 0x97, 0x04, 0xc6, 0x78, 0x38, 0x72, 0x4d, 0x2c, 0x52, 0x0d, 0x38, 0xe9, 0x9a, 0x6b, 0x62,
	0x0a, 0xd5, 0xc8, 0x9d, 0x38, 0x81, 0x3f, 0xe5, 0x27, 0x78, 0xd2, 0x35, 0x05, 0x8d, 0x1e, 0xd1,
	0x7f, 0x2a, 0x41, 0x95, 0xa5, 0x41, 0x1e, 0xe4, 0xf4, 0x7b, 0xa4, 0x67, 0xe2, 0x80, 0xab, 0x8c,
	0xf2, 0x17, 0x86, 0x9b, 0x56, 0x91, 0xc8, 0xa9, 0x38, 0xd8, 0xed, 0xc8, 0x33, 0x39, 0xa8, 0xcf,
	0x42, 0x8b, 0x0b, 0x72, 0x26, 0xf6, 0x03, 0xec, 0x0b, 0xb4, 0x9b, 0x8c, 0x76, 0x9b, 0x91, 0xf4,
	0xdf, 0x14, 0x40, 0xd7, 0x58, 0x10, 0x58, 0x65, 0x1f, 0xe0, 0x0f, 0x27, 0x98, 0x04, 0x69, 0xd1,
	0x4a, 0x41, 0x21, 0x2c, 0xa5, 0x0b, 0x61, 0xa2, 0xc0, 0x95, 0xf3, 0x0b, 0x5c, 0xa5, 0xa0, 0xc0,
	0x55, 0xf3, 0x0a, 0x5c, 0x6d, 0x71, 0x81, 0xab, 0x2f, 0x28, 0x70, 0x8d, 0xf8, 0x9d, 0xf6, 0x99,
	0x02, 0x27, 0x13, 0xfe, 0x13, 0xcf, 0x75, 0x08, 0x33, 0x01, 0xfb, 0xbe, 0xeb, 0xf3, 0xf4, 0x54,
	0xb8, 0x7f, 0x8c, 0xc2, 0xf2, 0xf7, 0xff, 0xd0, 0xe6, 0xdb, 0x36, 0x26, 0xc4, 0x38, 0xe4, 0x11,
	0x50, 0x07, 0x2d, 0x46, 0xbc, 0xc5, 0x69, 0x71, 0x84, 0xcb, 0x49, 0x84, 0xe3, 0x19, 0x5d, 0x49,
	0x64, 0xb4, 0xfe, 0x7d, 0x09, 0xd0, 0x3d, 0xcf, 0x5c, 0x1a, 0x90, 0xb8, 0xc8, 0x52, 0xf2, 0x23,
	0x59, 0x6c, 0x47, 0x12, 0xc5, 0x4a, 0x2e, 0x8a, 0xd5, 0x7c, 0x14, 0x6b, 0x05, 0x28, 0xd6, 0xf3,
	0x50, 0x6c, 0x2c, 0x46, 0x51, 0x5d, 0x80, 0x22, 0xc4, 0x51, 0x24, 0x70, 0x32, 0x11, 0xb3, 0x75,
	0x80, 0xa8, 0x7f, 0x00, 0x88, 0x7f, 0xcb, 0xcf, 0x1e, 0x28, 0xea, 0x60, 0x42, 0xd7, 0x5a, 0x1c,
	0xbc, 0x05, 0x9b, 0x6f, 0xe1, 0x60, 0x55, 0xde, 0xe9, 0x5f, 0x2a, 0xd0, 0x99, 0xc9, 0x5b, 0xa1,
	0x07, 0xaf, 0x43, 0x95, 0xe9, 0x10, 0x35, 0xbe, 0xb8, 0xb9, 0x60, 0x16, 0x70, 0x1e, 0xfd, 0x32,
	0x6c, 0x09, 0xa3, 0x2c, 0x4c, 0x64, 0xdd, 0xd4, 0xbf, 0x52, 0x00, 0xc5, 0xd9, 0x56, 0xe8, 0xcd,
	0x9b, 0xc0, 0x22, 0x66, 0x61, 0xa2, 0x95, 0x25, 0x9b, 0x25, 0xe6, 0x4f, 0xc8, 0xa5, 0xdf, 0x85,
	0x53, 0x61, 0x98, 0x45, 0xa3, 0xbe, 0x0a, 0xf4, 0xbe, 0x53, 0xe0, 0xdf, 0x73, 0x62, 0x57, 0xe8,
	0xf6, 0xbb, 0xc0, 0x7b, 0xe4, 0xe1, 0x31, 0x17, 0x2e, 0xc0, 0x7c, 0x41, 0xca, 0xf9, 0xd0, 0xa0,
	0x96, 0x17, 0x5b, 0xe9, 0xdf, 0x94, 0x60, 0x9b, 0xd7, 0xf6, 0xb0, 0x25, 0x5d, 0xc1, 0x37, 0x9a,
	0x6e, 0x32, 0xcb, 0xf3, 0x4d, 0x66, 0xa2, 0xc3, 0xaa, 0xe4, 0x75, 0x58, 0xd5, 0x05, 0x1d, 0x56,
	0x2d, 0xab, 0xc3, 0xaa, 0xe7, 0x74, 0x58, 0x8d, 0xc2, 0x0e, 0x4b, 0x9d, 0xef, 0xb0, 0x26, 0xf0,
	0xaf, 0x54, 0x78, 0xd6, 0x52, 0x56, 0x7e, 0x28, 0xc1, 0x36, 0xaf, 0xd6, 0xeb, 0x85, 0x25, 0x66,
	0x51, 0x25, 0x79, 0x0d, 0x26, 0x00, 0xab, 0xe6, 0x01, 0x56, 0x5b, 0x00, 0x58, 0x3d, 0x0b, 0xb0,
	0x46, 0x0e, 0x60, 0x6a, 0x21, 0x60, 0x90, 0x09, 0x58, 0x2a, 0x70, 0x6b, 0x01, 0xec, 0x73, 0x05,
	0xb6, 0xf9, 0xed, 0xf3, 0x27, 0x01, 0x8c, 0x06, 0x22, 0x65, 0xd0, 0x5a, 0x02, 0xe1, 0xb3, 0xbb,
	0x62, 0xad, 0x41, 0xd0, 0xbf, 0xe6, 0x37, 0xcd, 0xb3, 0x70, 0x74, 0x1f, 0xea, 0x42, 0x93, 0x28,
	0xb6, 0xd2, 0xa3, 0x7d, 0xc8, 0xa7, 0x7f, 0x31, 0x1b, 0x1f, 0xd8, 0xc4, 0xbe, 0x82, 0x98, 0x24,
	0x47, 0xba, 0x72, 0x7a, 0xa4, 0x4b, 0xcf, 0x34, 0x95, 0xf9, 0x99, 0x86, 0x44, 0x2d, 0x3d, 0xb7,
	0x69, 0x2d, 0xb9, 0xf1, 0xad, 0x12, 0xf5, 0xed, 0x6b, 0x8a, 0xc4, 0xe2, 0x7a, 0x96, 0x8e, 0x51,
	0x35, 0x33, 0x46, 0x09, 0x6b, 0xd7, 0x12, 0xa3, 0x4f, 0x95, 0xa8, 0x65, 0xfe, 0xa3, 0x63, 0x14,
	0xeb, 0xa8, 0xd7, 0x18, 0x80, 0x31, 0xef, 0xa8, 0xd7, 0xe3, 0x7c, 0xd4, 0x70, 0xaf, 0xdc, 0x41,
	0xda, 0x70, 0x53, 0xa1, 0xd2, 0x0d, 0x37, 0xb3, 0x80, 0xf3, 0xe8, 0xaf, 0xb1, 0x3e, 0xf2, 0x0e,
	0xf6, 0x1f, 0x63, 0xff, 0x3d, 0x1e, 0x97, 0x58, 0x2c, 0xcc, 0x89, 0x6d, 0x4f, 0x87, 0x9e, 0xe1,
	0x1b, 0xb6, 0x30, 0x0e, 0x18, 0xe9, 0x80, 0x52, 0xf4, 0xa7, 0x0a, 0x68, 0xf3, 0xcc, 0x2b, 0xf4,
	0xec, 0x1c, 0x6c, 0x10, 0x26, 0x7c, 0x18, 0x47, 0x50, 0x1d, 0xb4, 0x49, 0x5c, 0x25, 0x95, 0x25,
	0x8e, 0x4d, 0xbc, 0xc0, 0x12, 0x6f, 0x18, 0xe5, 0x41, 0x8b, 0x13, 0xef, 0x31, 0xda, 0xde, 0x15,
	0x50, 0x0f, 0xa2, 0x51, 0xba, 0x03, 0xad, 0x7b, 0xce, 0x91, 0xe3, 0x1e, 0x3b, 0x8c, 0xd6, 0x39,
	0x81, 0x00, 0x6a, 0x07, 0xd8, 0x27, 0xae, 0xd3, 0x51, 0x50, 0x0b, 0x1a, 0x57, 0x27, 0xc4, 0x72,
	0x30, 0x21, 0x9d, 0xd2, 0xde, 0xab, 0xd0, 0xdc, 0x8f, 0x5d, 0x83, 0x08, 0x36, 0x04, 0xab, 0xa0,
	0x76, 0x4e, 0xa0, 0x06, 0x54, 0xde, 0x76, 0x6d, 0xcc, 0x59, 0xef, 0x3c, 0xb2, 0x3c, 0xcf, 0x72,
	0x0e, 0x3b, 0xa5, 0xbd, 0x77, 0x40, 0x3d, 0x88, 0x92, 0x3f, 0xa6, 0x93, 0xd2, 0x3a, 0x27, 0x50,
	0x1b, 0x54, 0xca, 0xc6, 0x97, 0x0a, 0x5d, 0xde, 0x77, 0xfd, 0x23, 0xbe, 0x2c, 0xd1, 0xe5, 0x35,
	0x3c, 0x1e, 0xf3, 0x65, 0xb9, 0xff, 0xe3, 0x06, 0x74, 0xd2, 0xbf, 0x14, 0xa1, 0x63, 0x68, 0xf1,
	0x37, 0xb3, 0x21, 0x4b, 0x42, 0xd4, 0x2f, 0xc2, 0x7e, 0xfe, 0x71, 0xa9, 0x7b, 0x69, 0x29, 0x1e,
	0x81, 0xee, 0x31, 0xb4, 0x26, 0xac, 0x60, 0xc9, 0x2a, 0x9e, 0x7f, 0x44, 0x29, 0x56, 0x9c, 0xf5,
	0x88, 0x70, 0x0c, 0x2d, 0xfe, 0x86, 0x27, 0xab, 0x78, 0xfe, 0x51, 0xa0, 0x58, 0x71, 0xd6, 0x70,
	0xef, 0x80, 0x7a, 0x88, 0x03, 0xa1, 0xf5, 0xc5, 0x22, 0x09, 0xa9, 0x49, 0xbd, 0x7b, 0x41, 0x9e,
	0x41, 0xe8, 0x0b, 0xa0, 0x19, 0xea, 0xb3, 0x30, 0x41, 0x17, 0x25, 0x05, 0xcc, 0xc6, 0xe6, 0x6e,
	0x7f, 0x19, 0x16, 0xa1, 0xf5, 0x63, 0x05, 0xb6, 0x22, 0x37, 0xc3, 0xe1, 0x0f, 0xbd, 0x2c, 0x6b,
	0x7d, 0x72, 0xc2, 0xed, 0x5e, 0x59, 0x9a, 0x4f, 0x98, 0xf1, 0x04, 0x36, 0x44, 0x5e, 0x8b, 0xd6,
	0x06, 0x5d, 0x96, 0xcb, 0xd2, 0x64, 0x37, 0xd8, 0x7d, 0x69, 0x49, 0xae, 0x99, 0x7a, 0x91, 0xdd,
	0xd2, 0xea, 0xb3, 0x46, 0xa8, 0x62, 0xf5, 0xd9, 0xf3, 0xc3, 0x13, 0xd8, 0x10, 0x39, 0x2e, 0xad,
	0x3e, 0x6b, 0x20, 0x28, 0x56, 0x9f, 0xdd, 0xb5, 0x8b, 0xcc, 0x0b, 0x75, 0xcb, 0x64, 0x5e, 0x4a,
	0x71, 0x7f, 0x19, 0x96, 0xd9, 0x87, 0x1d, 0x96, 0x32, 0xf6, 0x33, 0x83, 0x6c, 0x29, 0x8b, 0xdd,
	0xde, 0xd2, 0xa5, 0x2c, 0x71, 0x05, 0xc7, 0x4a, 0x99, 0x9c, 0xe2, 0xf9, 0xbe, 0x52, 0xba, 0x94,
	0xa5, 0x15, 0x87, 0xa5, 0x4c, 0x4e, 0xf1, 0x7c, 0xb3, 0x26, 0x5d, 0xca, 0x12, 0x8a, 0xc3, 0x52,
	0xc6, 0xb4, 0x4a, 0x95, 0xb2, 0xb8, 0xca, 0x0b, 0xf2, 0x0c, 0x42, 0xdf, 0x27, 0x0a, 0x20, 0xaa,
	0x30, 0x79, 0x97, 0x23, 0x99, 0xea, 0x90, 0xd5, 0x98, 0x74, 0x5f, 0x59, 0x9e, 0x91, 0x5b, 0x72,
	0xf5, 0xdc, 0xfb, 0x9d, 0xf0, 0x74, 0x78, 0xf8, 0x69, 0x69, 0xee, 0x5a, 0x7d, 0x50, 0x63, 0xff,
	0x4d, 0x71, 0xe9, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xac, 0xd4, 0x21, 0x9b, 0x21, 0x00,
	0x00,
}
